# Generated by Django 4.2.7 on 2023-11-20 14:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cdr', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cdr',
            old_name='call_end_item',
            new_name='call_end_time',
        ),
        migrations.AddField(
            model_name='cdr',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
